name = "motorbike"
main = "index.js"
compatibility_date = "2025-07-04"

[site]
bucket = "."

# Custom domain updated
[[routes]]
[[routes]]
pattern = "motorbike.mbti.ninja"
custom_domain = true
zone_name = "mbti.ninja"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
