name = "motorbike"
main = "index.js"
compatibility_date = "2025-07-04"

[site]
bucket = "."

# Optional: configure a custom domain here or via CLI
[[routes]]
pattern = "motorbike.jdge.cc"
zone_name = "jdge.cc"
